### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by NkululekoThangelane** [uber-common/safemutations#1]
Hi am not able to run the any version of the simple.py script. no matter what arguments are i change.
Its seems to show the following:
python sm_simple.py --domain easy --mutation SM-G-SUM
Iteration, fitness, theta0, theta1
Traceback (most recent call last):
  File "sm_simple.py", line 405, in <module>
    main()
  File "sm_simple.py", line 392, in main
    fit = evaluate(m,theta)
  File "sm_simple.py", line 109, in evaluate
    return - error.sum().data.numpy()[0]
IndexError: too many indices for array

**Comment by GLJeff** [comment]
You're using a later version of pytorch than they did. Just remove the [0]
